import TASK1 from "./assets/imgs/task.jpg";
import TASK2 from "./assets/imgs/s1.jpg";
import TASK3 from "./assets/imgs/s2.jpg";
import TASK4 from "./assets/imgs/s3.jpg";
import TASK5 from "./assets/imgs/s4.jpg";

import VIDEO from "./assets/video/task-video.mp4";
export const Tasks = [
  {
    title: "HTML",
    category: "Task-CSS Grid Container",
    text: "Bu safargi mashqimiz Verstka yani HTML css dan bo'ladi huddi rasmda ko'rib turganizdek shakil chiqishi kerak bunga yordam cssning GRID xususiyatidan foydalansangiz bo'ladi...",
    image: [TASK1],
    id: 1,
  },
  {
    title: "HTML",
    category: "Task-HTML Forms",
    text: "Lorem 2 ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    image: [TASK2],
    id: 2,
  },
  {
    title: "HTML",
    category: "Task-HTML jadvallari",
    text: "Lorem 3 ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    image: [TASK3],
    id: 3,
  },
  {
    title: "HTML",
    category: "Task-HTML ro'yxatlari",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    image: [TASK4],
    id: 4,
  },
  {
    title: "HTML",
    category: "Task-HTML tartibsiz ro'yxatlar",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    image: [TASK5],
    id: 5,
  },
  {
    title: "HTML",
    category: "Task-HTML tartibli ro'yxatlar",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    image: [TASK3],
    id: 6,
  },
  {
    title: "HTML",
    category: "Task-HTML API'lari",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    image: [TASK2],
    id: 7,
  },
  {
    title: "HTML",
    category: "Task-HTML media",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    image: [TASK4],
    id: 8,
  },
  {
    title: "HTML",
    category: "Task-HTML grafika",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    image: [TASK5],
    id: 9,
  },
  {
    title: "HTML",
    category: "Task-HTML misollar",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    image: [TASK1],
    id: 10,
  },
  {
    title: "HTML",
    category: "Task-HTML havolalari",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    image: [TASK3],
    id: 11,
  },
  {
    title: "HTML",
    category: "Task-HTMLga kirish imkoniyati",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    image: [TASK3, TASK4, TASK1, TASK2],
    id: 12,
  },
  {
    title: "HTML",
    category: "Task-HTML formasi atributlari",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    image: [TASK5],
    id: 13,
  },
  {
    title: "HTML",
    category: "Task-HTML atributlari",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    image: [TASK2],
    id: 14,
  },
  {
    title: "HTML",
    category: "Task-HTML paragraflari",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    image: [TASK1],
    id: 15,
  },
  // css -----------------
  {
    title: "CSS",
    category: "CSS",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 1,
  },
  {
    title: "CSS",
    category: "CSS",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 2,
  },
  {
    title: "CSS",
    category: "CSS",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 3,
  },
  {
    title: "CSS",
    category: "CSS",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 4,
  },
  {
    title: "CSS",
    category: "CSS",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 5,
  },
  {
    title: "CSS",
    category: "CSS",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 6,
  },
  {
    title: "CSS",
    category: "CSS",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 7,
  },
  {
    title: "CSS",
    category: "CSS",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 8,
  },
  {
    title: "CSS",
    category: "CSS",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 9,
  },
  {
    title: "CSS",
    category: "CSS",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 10,
  },
  {
    title: "CSS",
    category: "CSS",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 11,
  },
  {
    title: "CSS",
    category: "CSS",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 12,
  },
  {
    title: "CSS",
    category: "CSS",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 13,
  },
  {
    title: "CSS",
    category: "CSS",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 14,
  },
  {
    title: "CSS",
    category: "CSS",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 15,
  },
  // bootstrap ---------
  {
    title: "BOOTSTRAP",
    category: "BOOTSTRAP",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 1,
  },
  {
    title: "BOOTSTRAP",
    category: "BOOTSTRAP",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 2,
  },
  {
    title: "BOOTSTRAP",
    category: "BOOTSTRAP",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 3,
  },
  {
    title: "BOOTSTRAP",
    category: "BOOTSTRAP",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 4,
  },
  {
    title: "BOOTSTRAP",
    category: "BOOTSTRAP",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 5,
  },
  {
    title: "BOOTSTRAP",
    category: "BOOTSTRAP",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 6,
  },
  {
    title: "BOOTSTRAP",
    category: "BOOTSTRAP",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 7,
  },
  {
    title: "BOOTSTRAP",
    category: "BOOTSTRAP",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 8,
  },
  {
    title: "BOOTSTRAP",
    category: "BOOTSTRAP",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 9,
  },
  {
    title: "BOOTSTRAP",
    category: "BOOTSTRAP",
    image: [TASK1],
    video: "",
    text: "Loreid: 10,m dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 10,
  },
  {
    title: "BOOTSTRAP",
    category: "BOOTSTRAP",
    image: [TASK1],
    video: "",
    text: "Loreid: 11,m dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 11,
  },
  {
    title: "BOOTSTRAP",
    category: "BOOTSTRAP",
    image: [TASK1],
    video: "",
    text: "Loreid: 12,m dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 12,
  },
  {
    title: "BOOTSTRAP",
    category: "BOOTSTRAP",
    image: [TASK1],
    video: "",
    text: "Loreid: 10,m dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 13,
  },
  {
    title: "BOOTSTRAP",
    category: "BOOTSTRAP",
    image: [TASK1],
    video: "",
    text: "Loreid: 11,m dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 14,
  },
  {
    title: "BOOTSTRAP",
    category: "BOOTSTRAP",
    image: [TASK1],
    video: "",
    text: "Loreid: 12,m dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 15,
  },
  // javascript ----------
  {
    title: "JAVASCRIPT",
    category: "JAVASCRIPT",
    image: [TASK1],
    video: VIDEO,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 1,
  },
  {
    title: "JAVASCRIPT",
    category: "JAVASCRIPT",
    image: [TASK1],
    video: VIDEO,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 2,
  },
  {
    title: "JAVASCRIPT",
    category: "JAVASCRIPT",
    image: [TASK1],
    video: VIDEO,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 3,
  },
  {
    title: "JAVASCRIPT",
    category: "JAVASCRIPT",
    image: [TASK1],
    video: VIDEO,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 4,
  },
  {
    title: "JAVASCRIPT",
    category: "JAVASCRIPT",
    image: [TASK1],
    video: VIDEO,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 5,
  },
  {
    title: "JAVASCRIPT",
    category: "JAVASCRIPT",
    image: [TASK1],
    video: VIDEO,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 6,
  },
  {
    title: "JAVASCRIPT",
    category: "JAVASCRIPT",
    image: [TASK1],
    video: VIDEO,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 7,
  },
  {
    title: "JAVASCRIPT",
    category: "JAVASCRIPT",
    image: [TASK1],
    video: VIDEO,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 8,
  },
  {
    title: "JAVASCRIPT",
    category: "JAVASCRIPT",
    image: [TASK1],
    video: VIDEO,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 9,
  },
  {
    title: "JAVASCRIPT",
    category: "JAVASCRIPT",
    image: [TASK1],
    video: VIDEO,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 10,
  },
  {
    title: "JAVASCRIPT",
    category: "JAVASCRIPT",
    image: [TASK1],
    video: VIDEO,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 11,
  },
  {
    title: "JAVASCRIPT",
    category: "JAVASCRIPT",
    image: [TASK1],
    video: VIDEO,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 12,
  },
  {
    title: "JAVASCRIPT",
    category: "JAVASCRIPT",
    image: [TASK1],
    video: VIDEO,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 13,
  },
  {
    title: "JAVASCRIPT",
    category: "JAVASCRIPT",
    image: [TASK1],
    video: VIDEO,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 14,
  },
  {
    title: "JAVASCRIPT",
    category: "JAVASCRIPT",
    image: [TASK1],
    video: VIDEO,
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 15,
  },
  // jquery --------------
  {
    title: "JQUERY",
    category: "JQUERY",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 1,
  },
  {
    title: "JQUERY",
    category: "JQUERY",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 2,
  },
  {
    title: "JQUERY",
    category: "JQUERY",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 3,
  },
  {
    title: "JQUERY",
    category: "JQUERY",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 4,
  },
  {
    title: "JQUERY",
    category: "JQUERY",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 5,
  },
  {
    title: "JQUERY",
    category: "JQUERY",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 6,
  },
  {
    title: "JQUERY",
    category: "JQUERY",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 7,
  },
  {
    title: "JQUERY",
    category: "JQUERY",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 8,
  },
  {
    title: "JQUERY",
    category: "JQUERY",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 9,
  },
  {
    title: "JQUERY",
    category: "JQUERY",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 10,
  },
  {
    title: "JQUERY",
    category: "JQUERY",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 11,
  },
  {
    title: "JQUERY",
    category: "JQUERY",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 12,
  },
  {
    title: "JQUERY",
    category: "JQUERY",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 13,
  },
  {
    title: "JQUERY",
    category: "JQUERY",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 14,
  },
  {
    title: "JQUERY",
    category: "JQUERY",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 15,
  },
  // react ---------
  {
    title: "REACT",
    category: "REACT",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 1,
  },
  {
    title: "REACT",
    category: "REACT",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 2,
  },
  {
    title: "REACT",
    category: "REACT",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 3,
  },
  {
    title: "REACT",
    category: "REACT",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 4,
  },
  {
    title: "REACT",
    category: "REACT",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 5,
  },
  {
    title: "REACT",
    category: "REACT",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 6,
  },
  {
    title: "REACT",
    category: "REACT",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 7,
  },
  {
    title: "REACT",
    category: "REACT",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 8,
  },
  {
    title: "REACT",
    category: "REACT",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 9,
  },
  {
    title: "REACT",
    category: "REACT",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 10,
  },
  {
    title: "REACT",
    category: "REACT",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 11,
  },
  {
    title: "REACT",
    category: "REACT",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 12,
  },
  {
    title: "REACT",
    category: "REACT",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 13,
  },
  {
    title: "REACT",
    category: "REACT",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 14,
  },
  {
    title: "REACT",
    category: "REACT",
    image: [TASK1],
    video: "",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque, numquam.",
    id: 15,
  },
];
